# -*- coding: utf-8 -*-
"""DealFlow360 Odoo Integration — Sale Order Model Extension.

Extends 'sale.order' with DealFlow governance fields, deal context calculation,
atomic approved change application, locking/unlocking, and validation guards.
"""

from __future__ import annotations

import dataclasses
import logging
from typing import Any, Dict, List, Optional, Union

try:
    from odoo import _, api, fields, models
    from odoo.exceptions import AccessError, UserError, ValidationError as OdooValidationError
except ImportError:
    from datetime import datetime as _dt

    class _MockDatetimeField:
        def __call__(self, *args, **kwargs):
            return None

        @classmethod
        def now(cls):
            return _dt.now().strftime("%Y-%m-%d %H:%M:%S")

        @classmethod
        def today(cls):
            return _dt.now().strftime("%Y-%m-%d")

    class _MockFields:
        def Char(self, *args, **kwargs): return None
        def Float(self, *args, **kwargs): return None
        def Boolean(self, *args, **kwargs): return None
        def Selection(self, *args, **kwargs): return None
        def Date(self, *args, **kwargs): return None
        def Many2one(self, *args, **kwargs): return None
        def One2many(self, *args, **kwargs): return None
        Datetime = _MockDatetimeField()

    class _MockAPI:
        @staticmethod
        def depends(*args):
            def decorator(f): return f
            return decorator
        @staticmethod
        def onchange(*args):
            def decorator(f): return f
            return decorator
        @staticmethod
        def constrains(*args):
            def decorator(f): return f
            return decorator

    class _MockModels:
        class Model:
            _name = None
            _inherit = None
            _description = None

            def write(self, vals):
                return True

            def action_confirm(self):
                return True

    class AccessError(Exception): pass
    class UserError(Exception): pass
    class OdooValidationError(Exception): pass
    def _(text): return text

    fields = _MockFields()
    api = _MockAPI()
    models = _MockModels()

try:
    from ..constants import (
        APPROVAL_STATES,
        APPROVAL_STATE_APPROVED,
        APPROVAL_STATE_DRAFT,
        APPROVAL_STATE_PENDING,
        APPROVAL_STATE_REAPPROVAL_REQUIRED,
        APPROVAL_STATE_REJECTED,
        CATEGORY_DISCOUNT_CEILINGS,
        DEFAULT_FINANCE_DISCOUNT_THRESHOLD,
        DEFAULT_MAX_MGR_DISCOUNT,
        DEFAULT_MAX_REP_DISCOUNT,
        HEALTH_STATUS_AT_RISK,
        HEALTH_STATUS_CRITICAL,
        HEALTH_STATUS_HEALTHY,
        HEALTH_STATUSES,
    )
    from ..schemas import AuthorizationError, CustomerDTO, DealContextDTO, OrderLineDTO, ValidationError
except (ImportError, ValueError):
    from dealflow_odoo.constants import (
        APPROVAL_STATES,
        APPROVAL_STATE_APPROVED,
        APPROVAL_STATE_DRAFT,
        APPROVAL_STATE_PENDING,
        APPROVAL_STATE_REAPPROVAL_REQUIRED,
        APPROVAL_STATE_REJECTED,
        CATEGORY_DISCOUNT_CEILINGS,
        DEFAULT_FINANCE_DISCOUNT_THRESHOLD,
        DEFAULT_MAX_MGR_DISCOUNT,
        DEFAULT_MAX_REP_DISCOUNT,
        HEALTH_STATUS_AT_RISK,
        HEALTH_STATUS_CRITICAL,
        HEALTH_STATUS_HEALTHY,
        HEALTH_STATUSES,
    )
    from dealflow_odoo.schemas import AuthorizationError, CustomerDTO, DealContextDTO, OrderLineDTO, ValidationError

_logger = logging.getLogger(__name__)


class SaleOrder(models.Model):
    """Extension of standard Odoo sale.order with DealFlow governance."""

    _inherit = "sale.order"

    # DealFlow Governance Fields
    dealflow_deal_id = fields.Char(
        string="DealFlow Deal ID",
        index=True,
        copy=False,
        help="Unique identifier of the DealFlow deal corresponding to this quotation.",
    )
    dealflow_risk_score = fields.Float(
        string="Risk Score",
        default=0.0,
        digits=(5, 2),
        help="Evaluated risk score (0.0 to 100.0) generated by DealFlow Deal Guardian.",
    )
    dealflow_approval_state = fields.Selection(
        selection=APPROVAL_STATES,
        string="DealFlow Approval State",
        default=APPROVAL_STATE_DRAFT,
        index=True,
        copy=False,
        tracking=True,
        help="Current governance approval status for this deal.",
    )
    dealflow_health_status = fields.Selection(
        selection=HEALTH_STATUSES,
        string="Deal Health Status",
        default=HEALTH_STATUS_HEALTHY,
        copy=False,
        tracking=True,
        help="Commercial and fulfillment health status.",
    )
    dealflow_last_evaluated_at = fields.Datetime(
        string="Last Evaluated At",
        copy=False,
        help="Timestamp of the most recent evaluation by DealFlow Deal Guardian.",
    )
    dealflow_locked = fields.Boolean(
        string="DealFlow Locked",
        default=False,
        copy=False,
        tracking=True,
        help="When True, prevents order confirmation until proper DealFlow governance approval is secured.",
    )
    dealflow_blended_discount = fields.Float(
        string="Blended Discount %",
        compute="_compute_blended_discount",
        store=True,
        digits=(5, 2),
        help="Weighted average discount percentage across all order lines.",
    )

    @api.depends("order_line.price_unit", "order_line.product_uom_qty", "order_line.discount")
    def _compute_blended_discount(self) -> None:
        """Compute weighted average discount across all active order lines."""
        for order in self:
            total_list_amount = 0.0
            total_discount_amount = 0.0
            for line in order.order_line:
                if line.display_type:
                    continue
                gross = (line.price_unit or 0.0) * (line.product_uom_qty or 0.0)
                total_list_amount += gross
                total_discount_amount += gross * ((line.discount or 0.0) / 100.0)

            if total_list_amount > 0.0:
                order.dealflow_blended_discount = round((total_discount_amount / total_list_amount) * 100.0, 2)
            else:
                order.dealflow_blended_discount = 0.0

    def action_get_deal_context(self, as_dict: bool = False) -> Union[DealContextDTO, Dict[str, Any]]:
        """Compute comprehensive deal context for DealFlow Guardian.

        Returns customer information, line-by-line categories, costs, list prices,
        discounts, margins, blended discount, recurring lines, and MRR/ARR.
        """
        self.ensure_one()

        partner = self.partner_id
        country_name = partner.country_id.name if partner and partner.country_id else None

        customer_dto = CustomerDTO(
            id=partner.id if partner else 0,
            name=partner.name if partner else "",
            email=partner.email if partner else None,
            phone=(partner.phone or getattr(partner, "mobile", None)) if partner else None,
            credit_limit=float(getattr(partner, "credit_limit", 0.0) or 0.0),
            total_invoiced=float(getattr(partner, "total_invoiced", 0.0) or 0.0),
            is_company=bool(partner.is_company) if partner else True,
            street=partner.street if partner else None,
            city=partner.city if partner else None,
            country=country_name,
        )

        line_dtos: List[OrderLineDTO] = []
        total_cost = 0.0
        has_recurring = False
        mrr = 0.0
        arr = 0.0

        for line in self.order_line:
            if line.display_type:
                continue

            product = line.product_id
            cat_name = product.categ_id.name if product and product.categ_id else "All"

            cost_price = float(getattr(line, "dealflow_cost_price", 0.0) or (product.standard_price if product else 0.0))
            line_qty = float(line.product_uom_qty or 0.0)
            line_cost = cost_price * line_qty
            total_cost += line_cost

            subtotal = float(line.price_subtotal or 0.0)
            margin = float(getattr(line, "dealflow_margin", 0.0) or (subtotal - line_cost))
            margin_percent = (margin / subtotal * 100.0) if subtotal > 0.0 else 0.0

            is_recurring = bool(getattr(line, "dealflow_is_recurring", False))
            interval = getattr(line, "dealflow_recurring_interval", None)

            if is_recurring:
                has_recurring = True
                if interval == "year":
                    arr += subtotal
                    mrr += subtotal / 12.0
                else:  # Default monthly interval
                    mrr += subtotal
                    arr += subtotal * 12.0

            line_dtos.append(
                OrderLineDTO(
                    id=line.id or 0,
                    product_id=product.id if product else 0,
                    product_name=product.name if product else (line.name or ""),
                    category_name=cat_name,
                    product_uom_qty=line_qty,
                    price_unit=float(line.price_unit or 0.0),
                    cost_price=cost_price,
                    discount=float(line.discount or 0.0),
                    price_subtotal=subtotal,
                    margin=round(margin, 2),
                    margin_percent=round(margin_percent, 2),
                    is_recurring=is_recurring,
                    recurring_interval=interval,
                )
            )

        amount_untaxed = float(self.amount_untaxed or 0.0)
        total_margin = amount_untaxed - total_cost
        margin_percent = (total_margin / amount_untaxed * 100.0) if amount_untaxed > 0.0 else 0.0

        dto = DealContextDTO(
            deal_id=self.dealflow_deal_id,
            order_id=self.id or 0,
            order_name=self.name or "",
            customer=customer_dto,
            state=self.state or "draft",
            date_order=str(self.date_order) if self.date_order else str(fields.Datetime.now()),
            currency=self.currency_id.name if self.currency_id else "USD",
            amount_untaxed=amount_untaxed,
            amount_tax=float(self.amount_tax or 0.0),
            amount_total=float(self.amount_total or 0.0),
            blended_discount=float(self.dealflow_blended_discount or 0.0),
            total_cost=round(total_cost, 2),
            total_margin=round(total_margin, 2),
            margin_percent=round(margin_percent, 2),
            lines=line_dtos,
            has_recurring_lines=has_recurring,
            mrr=round(mrr, 2),
            arr=round(arr, 2),
            dealflow_risk_score=float(self.dealflow_risk_score or 0.0),
            dealflow_approval_state=self.dealflow_approval_state or APPROVAL_STATE_DRAFT,
            dealflow_health_status=self.dealflow_health_status or HEALTH_STATUS_HEALTHY,
            dealflow_locked=bool(self.dealflow_locked),
        )

        if as_dict:
            return dataclasses.asdict(dto)
        return dto

    def action_dealflow_lock(self) -> bool:
        """Locks the order from confirmation until approved."""
        for order in self:
            order.write({"dealflow_locked": True})
            if hasattr(order, "message_post"):
                order.message_post(
                    body=_("DealFlow Governance: Order locked from confirmation pending approval."),
                    message_type="notification",
                    subtype_xmlid="mail.mt_note",
                )
        return True

    def action_dealflow_unlock(self, actor: Optional[Any] = None) -> bool:
        """Unlocks the order after approved, enforcing security role checks."""
        user = getattr(self.env, "user", None)
        target = actor if actor is not None else user
        if target:
            is_authorized = False
            if hasattr(target, "has_group"):
                is_authorized = (
                    target.has_group("dealflow_odoo.group_dealflow_sales_manager")
                    or target.has_group("dealflow_odoo.group_dealflow_finance")
                    or target.has_group("dealflow_odoo.group_dealflow_admin")
                    or getattr(target, "is_superuser", False)
                )
            elif isinstance(target, dict):
                role = target.get("role", "")
                is_authorized = role in ("manager", "sales_manager", "finance", "admin")
            elif isinstance(target, str):
                is_authorized = target.lower() in ("manager", "sales_manager", "finance", "admin")

            if not is_authorized:
                raise AuthorizationError(
                    _("Permission denied: Actor is not authorized to unlock DealFlow orders. Manager or Finance role required.")
                )

        for order in self:
            order.write({"dealflow_locked": False})
            if hasattr(order, "message_post"):
                order.message_post(
                    body=_("DealFlow Governance: Order unlocked."),
                    message_type="notification",
                    subtype_xmlid="mail.mt_note",
                )
        return True

    def action_dealflow_evaluate_governance(self) -> Dict[str, Any]:
        """Audits deal pricing, category ceilings, risk score, and health status."""
        self.ensure_one()
        self._compute_blended_discount()

        category_breaches = []
        has_negative_margin = False
        total_list = 0.0
        total_cost = 0.0

        for line in self.order_line:
            if line.display_type:
                continue
            cat_name = line.product_id.categ_id.name if line.product_id and line.product_id.categ_id else "All"
            ceiling = CATEGORY_DISCOUNT_CEILINGS.get(cat_name, DEFAULT_MAX_REP_DISCOUNT)
            disc = float(line.discount or 0.0)
            if disc > ceiling:
                category_breaches.append({
                    "line_id": line.id,
                    "product": line.name,
                    "category": cat_name,
                    "discount": disc,
                    "ceiling": ceiling,
                    "excess": disc - ceiling,
                })

            qty = float(line.product_uom_qty or 0.0)
            price_unit = float(line.price_unit or 0.0)
            cost = float(getattr(line, "dealflow_cost_price", 0.0) or (line.product_id.standard_price if line.product_id else 0.0))
            subtotal = (price_unit * qty) * (1.0 - disc / 100.0)
            line_cost = cost * qty
            total_list += price_unit * qty
            total_cost += line_cost
            if subtotal < line_cost:
                has_negative_margin = True

        total_margin = float(self.amount_untaxed or 0.0) - total_cost

        # Calculate explainable risk score
        risk = 0.0
        # Blended discount excess over rep threshold
        if self.dealflow_blended_discount > DEFAULT_MAX_REP_DISCOUNT:
            risk += (self.dealflow_blended_discount - DEFAULT_MAX_REP_DISCOUNT) * 1.5

        # Category breach penalty
        for b in category_breaches:
            risk += b["excess"] * 2.0 + 15.0

        # Negative margin penalty
        if total_margin < 0.0 or has_negative_margin:
            risk += 35.0

        # Free deal penalty (100% discount)
        is_free_deal = any(float(line.discount or 0.0) >= 100.0 for line in self.order_line if not line.display_type) or (total_list > 0 and self.dealflow_blended_discount >= 100.0)
        if is_free_deal:
            risk = 100.0

        risk_score = round(min(100.0, max(0.0, risk)), 2)
        self.dealflow_risk_score = risk_score

        # Determine health status and finance lock
        if is_free_deal or self.dealflow_blended_discount >= DEFAULT_FINANCE_DISCOUNT_THRESHOLD or total_margin < 0.0:
            self.dealflow_health_status = HEALTH_STATUS_CRITICAL
            if self.dealflow_approval_state != APPROVAL_STATE_APPROVED:
                self.dealflow_locked = True
        elif category_breaches or self.dealflow_blended_discount > DEFAULT_MAX_REP_DISCOUNT:
            self.dealflow_health_status = HEALTH_STATUS_AT_RISK
            if self.dealflow_approval_state != APPROVAL_STATE_APPROVED:
                self.dealflow_locked = True
        else:
            self.dealflow_health_status = HEALTH_STATUS_HEALTHY

        self.dealflow_last_evaluated_at = fields.Datetime.now()
        return {
            "risk_score": self.dealflow_risk_score,
            "health_status": self.dealflow_health_status,
            "dealflow_locked": self.dealflow_locked,
            "category_breaches": category_breaches,
            "is_free_deal": is_free_deal,
            "has_negative_margin": has_negative_margin,
        }

    def action_dealflow_apply_approved_change(self, approved_changes: Dict[str, Any]) -> bool:
        """Atomically applies updated discounts and terms, sets approval state to 'approved', and unlocks order.

        Args:
            approved_changes: Dictionary containing approved line discounts, terms, and metadata.
                - line_discounts or target_line_discounts: Dict[line_id -> discount_float]
                - lines: List[Dict[line_id, discount]]
                - discount: float (global fallback discount)
                - payment_term_id: int
                - terms or note: str
                - validity_date: date/str
                - dealflow_deal_id: str
                - dealflow_risk_score: float
                - dealflow_health_status: str
        """
        self.ensure_one()
        user = getattr(self.env, "user", None)
        if user:
            is_portal = (
                user.has_group('base.group_portal')
                or user.has_group('dealflow_odoo.group_dealflow_portal')
                or not user.has_group('base.group_user')
            )
            if is_portal:
                raise AccessError(_("Privilege Escalation Blocked: Portal users cannot apply approved changes."))

            if user.has_group('dealflow_odoo.group_dealflow_sales_rep'):
                is_finance_or_admin = (
                    user.has_group('dealflow_odoo.group_dealflow_finance')
                    or user.has_group('dealflow_odoo.group_dealflow_admin')
                )
                if not is_finance_or_admin:
                    discounts = []
                    if "discount" in approved_changes:
                        discounts.append(float(approved_changes["discount"]))
                    if "target_line_discounts" in approved_changes and isinstance(approved_changes["target_line_discounts"], dict):
                        discounts.extend(float(d) for d in approved_changes["target_line_discounts"].values())
                    if "line_discounts" in approved_changes and isinstance(approved_changes["line_discounts"], dict):
                        discounts.extend(float(d) for d in approved_changes["line_discounts"].values())
                    if "lines" in approved_changes and isinstance(approved_changes["lines"], list):
                        discounts.extend(float(item.get("discount", 0.0)) for item in approved_changes["lines"] if isinstance(item, dict))

                    if any(d > DEFAULT_FINANCE_DISCOUNT_THRESHOLD for d in discounts):
                        raise AccessError(
                            _("Privilege Escalation Blocked: Sales Rep cannot approve discounts exceeding %s%% (Finance approval required).")
                            % DEFAULT_FINANCE_DISCOUNT_THRESHOLD
                        )

        order = self.with_context(dealflow_skip_reapproval=True)

        # 1. Update line discounts
        line_discounts = (
            approved_changes.get("line_discounts")
            or approved_changes.get("target_line_discounts")
            or {}
        )
        if isinstance(line_discounts, dict):
            for line_id_key, disc_val in line_discounts.items():
                try:
                    line_id = int(line_id_key)
                except (ValueError, TypeError):
                    continue
                line = order.order_line.filtered(lambda l: l.id == line_id)
                if line:
                    line.write({
                        "discount": float(disc_val),
                        "dealflow_approved_discount": float(disc_val),
                    })

        if "lines" in approved_changes and isinstance(approved_changes["lines"], list):
            for item in approved_changes["lines"]:
                if isinstance(item, dict):
                    line_id = item.get("line_id") or item.get("id")
                    disc = item.get("discount")
                    if line_id is not None and disc is not None:
                        line = order.order_line.filtered(lambda l: l.id == int(line_id))
                        if line:
                            line.write({
                                "discount": float(disc),
                                "dealflow_approved_discount": float(disc),
                            })

        if "discount" in approved_changes and not line_discounts and "lines" not in approved_changes:
            global_disc = float(approved_changes["discount"])
            for line in order.order_line:
                if not line.display_type:
                    line.write({
                        "discount": global_disc,
                        "dealflow_approved_discount": global_disc,
                    })

        # 2. Update order-level terms and governance state
        order_vals: Dict[str, Any] = {
            "dealflow_approval_state": APPROVAL_STATE_APPROVED,
            "dealflow_locked": False,
            "dealflow_last_evaluated_at": fields.Datetime.now(),
        }

        if "payment_term_id" in approved_changes:
            order_vals["payment_term_id"] = approved_changes["payment_term_id"]

        if "validity_date" in approved_changes:
            order_vals["validity_date"] = approved_changes["validity_date"]

        if "terms" in approved_changes:
            order_vals["note"] = approved_changes["terms"]
        elif "note" in approved_changes:
            order_vals["note"] = approved_changes["note"]

        if "dealflow_deal_id" in approved_changes:
            order_vals["dealflow_deal_id"] = approved_changes["dealflow_deal_id"]

        if "dealflow_risk_score" in approved_changes:
            order_vals["dealflow_risk_score"] = float(approved_changes["dealflow_risk_score"])

        if "dealflow_health_status" in approved_changes:
            order_vals["dealflow_health_status"] = approved_changes["dealflow_health_status"]

        order.write(order_vals)

        # 3. Log notification in chatter
        if hasattr(order, "message_post"):
            order.message_post(
                body=_(
                    "DealFlow Governance: Approved changes applied atomically. "
                    "Deal marked as Approved and Unlocked for execution."
                ),
                message_type="notification",
                subtype_xmlid="mail.mt_note",
            )

        return True

    def action_dealflow_confirm(self) -> Any:
        """Validates DealFlow governance rules before order confirmation.

        Raises:
            AccessError: If order confirmation is attempted by a portal customer.
            UserError: If discount exceeds threshold or dealflow_locked is True
                       and dealflow_approval_state != 'approved'.
        """
        user = getattr(self.env, "user", None)
        if user and (
            user.has_group('base.group_portal')
            or user.has_group('dealflow_odoo.group_dealflow_portal')
            or not user.has_group('base.group_user')
        ):
            raise AccessError(_("Privilege Escalation Blocked: Portal users cannot confirm sales orders directly."))

        ctx = getattr(self.env, "context", {}) or getattr(self, "_context", {}) or {}
        bypass = ctx.get("dealflow_bypass_check", False)
        if not bypass:
            for order in self:
                exceeds_threshold = (
                    order.dealflow_blended_discount > DEFAULT_MAX_REP_DISCOUNT
                    or any(
                        line.discount > DEFAULT_MAX_REP_DISCOUNT
                        for line in order.order_line
                        if not line.display_type
                    )
                )
                has_category_breach = any(
                    line.discount > CATEGORY_DISCOUNT_CEILINGS.get(
                        line.product_id.categ_id.name if line.product_id and line.product_id.categ_id else "All",
                        DEFAULT_MAX_REP_DISCOUNT
                    )
                    for line in order.order_line
                    if not line.display_type
                )
                if (order.dealflow_locked or exceeds_threshold or has_category_breach) and order.dealflow_approval_state != APPROVAL_STATE_APPROVED:
                    raise UserError(_("Order locked pending DealFlow approval"))

        if hasattr(super(), "action_confirm"):
            return super().action_confirm()
        return True

    def action_confirm(self) -> Any:
        """Override standard confirm action to enforce DealFlow governance."""
        return self.action_dealflow_confirm()

    def write(self, vals: Dict[str, Any]) -> bool:
        """Governance hook detecting discount or commercial terms modification after approval.

        If discount is modified on lines or terms change after approval,
        auto-transitions dealflow_approval_state to 'reapproval_required'
        and dealflow_locked=True.
        """
        # Validate discount boundary in order_line commands
        if "order_line" in vals and isinstance(vals["order_line"], list):
            for cmd in vals["order_line"]:
                if isinstance(cmd, (list, tuple)) and len(cmd) >= 3 and isinstance(cmd[2], dict):
                    line_data = cmd[2]
                    if "discount" in line_data:
                        d = float(line_data["discount"])
                        if d < 0.0 or d > 100.0:
                            raise OdooValidationError(_(f"Discount must be between 0.0% and 100.0%. Received: {d}%."))
                    if "product_uom_qty" in line_data:
                        q = float(line_data["product_uom_qty"])
                        if q <= 0.0:
                            raise OdooValidationError(_(f"Quantity must be strictly positive. Received: {q}."))
        user = getattr(self.env, "user", None)
        if user and vals.get("dealflow_approval_state") == APPROVAL_STATE_APPROVED:
            is_portal = (
                user.has_group('base.group_portal')
                or user.has_group('dealflow_odoo.group_dealflow_portal')
                or not user.has_group('base.group_user')
            )
            if is_portal:
                raise AccessError(_("Privilege Escalation Blocked: Portal users cannot update order approval state."))

            if user.has_group('dealflow_odoo.group_dealflow_sales_rep'):
                is_finance_or_admin = (
                    user.has_group('dealflow_odoo.group_dealflow_finance')
                    or user.has_group('dealflow_odoo.group_dealflow_admin')
                )
                if not is_finance_or_admin:
                    for order in self:
                        if order.dealflow_blended_discount > DEFAULT_FINANCE_DISCOUNT_THRESHOLD:
                            raise AccessError(
                                _("Privilege Escalation Blocked: Sales Rep cannot approve order exceeding %s%% discount (Finance approval required).")
                                % DEFAULT_FINANCE_DISCOUNT_THRESHOLD
                            )

        ctx = getattr(self.env, "context", {}) or getattr(self, "_context", {}) or {}
        if ctx.get("dealflow_skip_reapproval"):
            return super().write(vals)

        terms_fields = {"payment_term_id", "note", "terms_type", "validity_date", "pricelist_id"}
        terms_modified = bool(terms_fields & set(vals.keys()))

        lines_modified = False
        if "order_line" in vals and isinstance(vals["order_line"], list):
            for cmd in vals["order_line"]:
                if isinstance(cmd, (list, tuple)) and len(cmd) >= 2:
                    cmd_code = cmd[0]
                    # 0: create, 1: write, 2: unlink, 3: remove link, 5: clear all
                    if cmd_code in (2, 3, 5):
                        lines_modified = True
                        break
                    elif cmd_code in (0, 1) and len(cmd) >= 3 and isinstance(cmd[2], dict):
                        line_data = cmd[2]
                        if any(f in line_data for f in ("discount", "price_unit", "product_uom_qty")):
                            lines_modified = True
                            break

        orders_to_reapprove = []
        if terms_modified or lines_modified:
            for order in self:
                if order.dealflow_approval_state == APPROVAL_STATE_APPROVED:
                    orders_to_reapprove.append(order)

        res = super().write(vals)

        if orders_to_reapprove:
            for order in orders_to_reapprove:
                order.with_context(dealflow_skip_reapproval=True).write({
                    "dealflow_approval_state": APPROVAL_STATE_REAPPROVAL_REQUIRED,
                    "dealflow_locked": True,
                })
                if hasattr(order, "message_post"):
                    order.message_post(
                        body=_(
                            "DealFlow Governance: Order terms or line discounts were modified after approval. "
                            "Approval state transitioned to 'Reapproval Required' and order locked."
                        ),
                        message_type="notification",
                        subtype_xmlid="mail.mt_note",
                    )

        return res
